# Generated by Django 5.0.1 on 2024-02-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('member_name', models.CharField(max_length=200)),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
