# Generated by Django 5.0.1 on 2024-02-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0004_remove_records_book_name_remove_records_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='book_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='records',
            name='member_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='records',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='member_id',
            field=models.IntegerField(),
        ),
    ]
