# Generated by Django 5.0.1 on 2024-02-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0005_records_book_name_records_member_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='records',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='records',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libra.library'),
        ),
        migrations.AlterField(
            model_name='records',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libra.datamember'),
        ),
    ]
